package dao;

import java.sql.SQLException;

import util.DBConnector;

public class Test {






	public static void main(String[] args) {

		String loginUserId;
		String loginUserPassword;
		String userName;
		String year;
		String streetAddress;
		String sex;
		String phoneNumber;

		loginUserId ="tanaka";
		loginUserPassword="6161";
		userName="田中";
		year ="36";
		streetAddress="東京";
		sex="男";
		phoneNumber="6161";

		DBConnector dbconnector = new DBConnector();

		UserCreateCompleteDAO dao = new UserCreateCompleteDAO();

		dbconnector.getConnection();

		try {
			dao.cerateUser(loginUserId, loginUserPassword, userName, year, streetAddress, sex, phoneNumber);

			System.out.println("全件表示↓");

			dao.selectAll();
		} catch (SQLException e) {
			System.out.println("エラー発生");
			e.printStackTrace();
		}
		System.out.println("dao正常に作動");
	}



}
